rsa:
    private-key: classpath:certificates/private.pem
    public-key: classpath:certificates/public.pem
spring:
    datasource:
        url: jdbc:postgresql://containers-us-west-176.railway.app:7374/railway
        username: postgres
        password: 2WE5DegBMqmg9ctSH8PY
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
