rsa:
    private-key: classpath:certificates/private.pem
    public-key: classpath:certificates/public.pem
spring:
    datasource:
        url: jdbc:h2:file:~/taskManager
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
            path: /db

